name: alzahimer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  tflite: ^1.1.2
  page_transition: ^2.0.9
  awesome_dialog: ^3.0.2
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  cloud_firestore: ^4.4.4
  flutter_native_splash: ^2.2.19
  firebase_storage: ^11.1.1
  transparent_image: ^2.0.1
  flutter_slidable: ^2.0.0
  flutter_typeahead: ^3.0.1
  flutter_bloc: ^8.1.2
  icon_broken: ^1.1.0
  conditional_builder_null_safety: ^0.0.6
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_offline: ^2.1.0
  screenshot: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  shared_preferences: ^2.0.15
  hydrated_bloc: ^9.1.2

  image_picker: ^0.8.6+1
  image_gallery_saver: ^1.7.1
 # screenshot: ^2.1.0
  gradient_borders: ^1.0.0
  circular_profile_avatar: ^2.0.5

  permission_handler: ^10.0.0
  lottie: ^1.3.0
  path_provider: ^2.0.3
  uuid: ^3.0.4
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_doctor.png
  android_gravity: fill
  android: true
  ios: true
  color_dark: "#ffffff"
  image_dark: assets/images/splash_doctor.png


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
